server:
  port: 8082

spring:
  application:
    name: file-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/file_service_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: dominik
    password: dominik
  jpa:
    open-in-view: false #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  kafka:
    bootstrap:
      server: localhost:29092
    client:
      timeout: 30000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/