server:
  port: 8082

spring:
  application:
    name: file-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  kafka:
    bootstrap:
      server: localhost:29092
    client:
      timeout: 30000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/