server:
  port: 8081

spring:
  application:
    name: measurement-service
  sql:
    init:
      data-locations: classpath:sql/*.sql # or create DataSourceInitializer Bean
      mode: always

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/measurement_service_db
      username: dominik
      password: dominik
      maxPoolSize: 30


logging:
  level:
    org:
      springframework:
        data: DEBUG
        jdbc:
          core: TRACE
