server:
  port: 8083

spring:
  application:
    name: data-input-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data_input_service_db
    username: dominik
    password: dominik
  jpa:
    open-in-view: false #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot

  kafka:
    bootstrap:
      server: pkc-4ygn6.europe-west3.gcp.confluent.cloud:9092
    client:
      timeout: 30000
