server:
  port: 8090

spring:
  application:
    name: discovery-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    maxThreadsForPeerReplication: 0 # becasue we are not using default port, we have to stop replication attempts