server:
  port: 8085

spring:
  application:
    name: device-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/device_service_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: dominik
    password: dominik
  jpa:
    open-in-view: false #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap:
      server: localhost:29092
    client:
      timeout: 30000

logging:
  level:
    com:
      netflix:
        discovery: off

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/